title: DataEndure ZTNA
email: ztna@dataendure.com
description: >- # this means to ignore newlines until "baseurl:"
  DataEndure ZTNA

baseurl: "/"
url: "" # the base hostname & protocol for your site, e.g. http://example.com

linkedin: https://www.linkedin.com/company/dataendure/
twitter: https://twitter.com/dataendure
github: https://github.com

exclude:
  - README.md
  - Gemfile*
  - .sass-cache/
  - .jekyll-cache/
  - vendor
