title: DataEndure ZTNA powered by Banyan Security
email: banyan@dataendure.com
description: >- # this means to ignore newlines until "baseurl:"
  DataEndure ZTNA powered by Banyan Security

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

linkedin: https://www.linkedin.com/company/dataendure/
twitter: https://twitter.com/dataendure
github: https://github.com/dataendure

exclude:
  - README.md
  - Gemfile*
  - .sass-cache/
  - .jekyll-cache/
  - vendor